# Generated by Django 2.0.13 on 2019-07-12 10:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_document_section'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='check_delete',
            field=models.BooleanField(default=False, verbose_name='Пометка на удаление'),
        ),
        migrations.AddField(
            model_name='document',
            name='lead',
            field=models.BooleanField(default=False, verbose_name='Проведение'),
        ),
        migrations.AddField(
            model_name='document',
            name='uncheck_delete',
            field=models.BooleanField(default=False, verbose_name='Снятие пометки на удаление'),
        ),
        migrations.AddField(
            model_name='document',
            name='unlead',
            field=models.BooleanField(default=False, verbose_name='Отмена проведения'),
        ),
    ]
