# Generated by Django 2.0.13 on 2019-07-14 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20190712_1000'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='lead_redact',
            field=models.BooleanField(default=False, verbose_name='Изменение проведенных'),
        ),
    ]
