# Generated by Django 3.0.7 on 2020-06-21 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_document_lead_redact'),
    ]

    operations = [
        migrations.CreateModel(
            name='Zapros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='name', max_length=200)),
                ('problem', models.CharField(default='problem', max_length=200)),
            ],
        ),
    ]
