# Generated by Django 3.0.7 on 2020-06-22 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_finished'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='name',
            field=models.CharField(default='name', max_length=200, verbose_name='Имя'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='problem',
            field=models.TextField(default='problem', max_length=200, verbose_name='Проблема'),
        ),
    ]
