# Generated by Django 3.0.7 on 2020-06-23 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_auto_20200623_0110'),
    ]

    operations = [
        migrations.AddField(
            model_name='zapros',
            name='verification',
            field=models.IntegerField(default='123', verbose_name=2),
        ),
    ]
