# Generated by Django 3.0.7 on 2020-06-23 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_zapros_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.IntegerField(default=374, verbose_name=374),
        ),
    ]
