# Generated by Django 3.0.7 on 2020-06-23 23:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20200624_0035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='PwwqCSpXjzJcIbOe6WabP7FXs8BWpdDS', max_length=200, verbose_name='PwwqCSpXjzJcIbOe6WabP7FXs8BWpdDS'),
        ),
    ]
