# Generated by Django 2.1 on 2020-06-24 22:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_auto_20200624_0212'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Почта'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='problem',
            field=models.TextField(default='', max_length=200, verbose_name='Опишите проблему'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='RAZReK6d4geOWIm4x8VQvrRQr7Rj6p1h', max_length=200, verbose_name='RAZReK6d4geOWIm4x8VQvrRQr7Rj6p1h'),
        ),
    ]
