# Generated by Django 2.1 on 2020-06-25 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200625_0154'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='company',
            field=models.CharField(choices=[('pd', 'Planeta Doors'), ('ar', 'ИП Арынов'), ('bt', 'Beltaus Trading'), ('ts', 'ИП Таишев'), ('ki', 'ТОО Kendala Impex'), ('co', 'ЦО'), ('un', 'undefined')], default='pd', max_length=2, verbose_name='Компания'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='inventNumber',
            field=models.CharField(default='', max_length=200, verbose_name='Инвентаризационный Номер'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Модель'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='serialNumber',
            field=models.CharField(default='', max_length=200, verbose_name='Серийный Номер'),
        ),
        migrations.AlterField(
            model_name='worker',
            name='name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='worker',
            name='surname',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='EZKV3gfx7Gi2qywsgabHqJVjEbfaFqG1', max_length=200, verbose_name='EZKV3gfx7Gi2qywsgabHqJVjEbfaFqG1'),
        ),
    ]
