# Generated by Django 3.0.7 on 2020-06-25 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0013_auto_20200625_2115'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner',
            name='used_loads',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='u01iYt5CHm9KtMQiREAVooRIsozKeuwZ', max_length=200, verbose_name='u01iYt5CHm9KtMQiREAVooRIsozKeuwZ'),
        ),
    ]
