# Generated by Django 3.0.7 on 2020-06-28 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0015_auto_20200625_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='dwPSZ7BZPC5hYXmC0PKK1BWpIbjtP0RD', max_length=200, verbose_name='dwPSZ7BZPC5hYXmC0PKK1BWpIbjtP0RD'),
        ),
    ]
