# Generated by Django 3.0.7 on 2020-06-28 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0017_auto_20200628_1415'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='yu3Ujt8VcM7iybF3RlIH4y3a5sn8LT36', max_length=200, verbose_name='yu3Ujt8VcM7iybF3RlIH4y3a5sn8LT36'),
        ),
        migrations.AlterModelTable(
            name='historicaltoner',
            table='blog_toner_history',
        ),
    ]
