# Generated by Django 3.0.7 on 2020-06-28 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0018_auto_20200628_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='history', max_length=100, verbose_name='History')),
                ('changed', models.CharField(default='history', max_length=100, verbose_name='History')),
            ],
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='Sqtsnmvj51zjjDKIW79ziMlC9mXxgmkf', max_length=200, verbose_name='Sqtsnmvj51zjjDKIW79ziMlC9mXxgmkf'),
        ),
        migrations.DeleteModel(
            name='HistoricalToner',
        ),
    ]
