# Generated by Django 3.0.7 on 2020-06-28 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0019_auto_20200628_1520'),
    ]

    operations = [
        migrations.RenameField(
            model_name='history',
            old_name='changed',
            new_name='new',
        ),
        migrations.AddField(
            model_name='history',
            name='old',
            field=models.CharField(default='history', max_length=100, verbose_name='History'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='ERflKv4C2HTayNtAMME56eJwfVlaTlC6', max_length=200, verbose_name='ERflKv4C2HTayNtAMME56eJwfVlaTlC6'),
        ),
    ]
