# Generated by Django 3.0.7 on 2020-06-28 13:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0022_auto_20200628_1601'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='dJgcjeFyMD5zGVD2kW6Vh0bnUTgHD99l', max_length=200, verbose_name='dJgcjeFyMD5zGVD2kW6Vh0bnUTgHD99l'),
        ),
    ]
