# Generated by Django 3.0.7 on 2020-06-28 15:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0023_auto_20200628_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='laptop',
            name='family',
            field=models.CharField(choices=[('t1', 'Ноутбук'), ('t2', 'Компьютер'), ('t3', 'Монитор'), ('t4', 'Дисплей')], default='t1', max_length=2, verbose_name='Тип Техники'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='IrM0W1zrWzI3Eqch8rVAxRZUleJCwsSl', max_length=200, verbose_name='IrM0W1zrWzI3Eqch8rVAxRZUleJCwsSl'),
        ),
    ]
