# Generated by Django 3.0.7 on 2020-06-28 15:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0024_auto_20200628_2103'),
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=200, verbose_name='Модель')),
            ],
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='OWLZqWUCepIoRQebCXQMpE6hnfrXzrIJ', max_length=200, verbose_name='OWLZqWUCepIoRQebCXQMpE6hnfrXzrIJ'),
        ),
        migrations.AddField(
            model_name='laptop',
            name='brand',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.Brand'),
        ),
    ]
