# Generated by Django 3.0.7 on 2020-06-28 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200628_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='email',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='hUG2W2kZ2NcdITeCcxs2pWVRDY0tfbMz', max_length=200, verbose_name='hUG2W2kZ2NcdITeCcxs2pWVRDY0tfbMz'),
        ),
    ]
