# Generated by Django 2.1 on 2020-06-28 16:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0025_auto_20200628_2124'),
        ('blog', '0014_auto_20200625_2056'),
    ]

    operations = [
    ]
