# Generated by Django 3.0.7 on 2020-06-29 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200629_0042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='workerID',
        ),
        migrations.AlterField(
            model_name='toner',
            name='name',
            field=models.CharField(default='F217', max_length=100, verbose_name='Toner'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='FKYs2MdNHgNGqkUbannAOw7WjI7WtRTd', max_length=200, verbose_name='FKYs2MdNHgNGqkUbannAOw7WjI7WtRTd'),
        ),
    ]
