# Generated by Django 2.1 on 2020-06-29 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0026_auto_20200629_0042'),
        ('blog', '0026_merge_20200628_2210'),
    ]

    operations = [
    ]
