# Generated by Django 3.0.7 on 2020-06-29 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_auto_20200629_1612'),
    ]

    operations = [
        migrations.AddField(
            model_name='toner',
            name='accept',
            field=models.CharField(default='', max_length=100, verbose_name='Совместимые'),
        ),
        migrations.AlterField(
            model_name='toner',
            name='name',
            field=models.CharField(choices=[('t1', 'F217'), ('t2', 'ANB-12'), ('t3', '75zD')], default='t1', max_length=2, verbose_name='Тонер'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='6LKHv59ZD05UhySNnn8YmJKjTVrB4s1k', max_length=200, verbose_name='6LKHv59ZD05UhySNnn8YmJKjTVrB4s1k'),
        ),
    ]
