# Generated by Django 2.1 on 2020-06-29 10:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0027_merge_20200629_1555'),
        ('blog', '0028_auto_20200629_1630'),
    ]

    operations = [
    ]
