# Generated by Django 3.0.7 on 2020-06-30 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0029_merge_20200629_1636'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='server',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='toner',
            name='name',
            field=models.CharField(choices=[('t1', 'TRHM102'), ('t2', 'CE285A'), ('t3', 'TRSUNIV'), ('t4', 'T125-K')], default='t1', max_length=2, verbose_name='Тонер'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='KjxHj8jNJ1LxLyqNPiGXgO5TrVZGincL', max_length=200, verbose_name='KjxHj8jNJ1LxLyqNPiGXgO5TrVZGincL'),
        ),
    ]
