# Generated by Django 3.0.7 on 2020-06-30 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0030_auto_20200630_0742'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='worker',
            name='server',
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='UZTiRdcMcbOX9YntvE4cX22PY1mxaReS', max_length=200, verbose_name='UZTiRdcMcbOX9YntvE4cX22PY1mxaReS'),
        ),
    ]
