# Generated by Django 2.1 on 2020-06-30 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0033_auto_20200630_1524'),
    ]

    operations = [
        migrations.AlterField(
            model_name='laptop',
            name='family',
            field=models.CharField(choices=[('t1', 'Ноутбук'), ('t2', 'Компьютер'), ('t3', 'Монитор'), ('t4', 'Принтер')], default='t1', max_length=2, verbose_name='Тип Техники'),
        ),
        migrations.AlterField(
            model_name='laptop',
            name='inventNumber',
            field=models.CharField(default='', max_length=200, verbose_name='Инвентаризационный Номер'),
        ),
        migrations.AlterField(
            model_name='zapros',
            name='verification',
            field=models.CharField(default='xQ3QE984P9yWktoJrkZp6pTwQvp5CQXB', max_length=200, verbose_name='xQ3QE984P9yWktoJrkZp6pTwQvp5CQXB'),
        ),
    ]
